version: '3'

volumes:
  pg-data:
    driver: local

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: keycloak-discourse
      POSTGRES_DB: keycloak-discourse

  keycloak-discourse:
    image: code-house/keycloak-discourse:latest
    command: ["start-dev"]
    environment:
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak-discourse
      KC_DB_USERNAME: keycloak-discourse
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      JAVA_OPTS: >
        -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006

      #-Dhttp.proxyHost=192.168.2.106 -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
      #HTTP_PROXY: http://192.168.2.106:8888
    ports:
      - 8080:8080
      - 5006:5006
    depends_on:
      - postgres
